#!/bin/sh
# credit: http://mark-story.com/posts/view/using-git-commit-hooks-to-prevent-stupid-mistakes

if [ "x$1" == "x--about" ]
then
  echo 'Fails commits with `debugger` statements'
  exit 0
fi

if git diff-index --name-only HEAD | grep -v '^Gemfile' | xargs git grep --cached debugger --
then
  # Success from git-grep means there was a match, which is bad.
  exit 1
fi
