#!/bin/sh

if [ "x$1" == "x--about" ]
then
  echo 'Fails commits with `debugger` statements'
  exit 0
fi

files()
{
  git diff-index --name-only HEAD | grep -v '^Gemfile'
}

if files > /dev/null
then
  if files | xargs git grep --cached debugger --
  then
    # Success from git-grep means there was a match, which is bad.
    exit 1
  fi
fi
exit 0
